import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/Layout/Footer";
import { Topbar } from "../components/Layout/Topbar";
import { cn } from "../utils/tailwindMerge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <main>
          <div
            className={cn([
              "grid",
              "grid-rows-[auto_1fr_auto]",
              "min-h-screen",
            ])}
          >
            <Topbar />
            <div>{children}</div>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
